id: P000776
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1017690
  title: ཟང་ཟུ་ཝེན་ཧུཨ་ཡུ་ཀང་བ་ཕེ༹ང་qཨིང
  author: ''
  volumes:
    8704afa805a5427dab95480cbde8828a:
      image_group_id: I1GS105583
      title: ''
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
