id: I8085A048
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:29:44+00:00'
last_modified: '2022-06-07T13:48:45.912964+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017690
  title: ཟང་ཟུ་ཝེན་ཧུཨ་ཡུ་ཀང་བ་ཕེ༹ང་qཨིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C2D6:
      image_group_id: I1GS105583
      title: ''
      total_pages: 426
      order: 1
      base_file: C2D6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
